FROM node:8.11.1

# Maintainer
MAINTAINER Diogo Bemfica "diogo.fragabemfica@gmail.com"

RUN apt-get update && apt-get clean
RUN npm i pm2 -g --silent

# BUILD
WORKDIR /home/node
RUN git clone https://github.com/MikaAssistant/mika-nlp.git app
WORKDIR /home/node/app
ENV NODE_ENV=production
ENV TZ=America/Sao_Paulo

EXPOSE 9000
CMD [ "pm2-docker", "app.js" ]
