version: '2'
services:
    router:
        build: ./router
        image: mika/router
        container_name: mika-router
        ports:
            - "4000:4000"
        restart: always
    kernel:
        build: ./kernel
        image: mika/kernel
        container_name: mika-kernel
        volumes:
            - ./database:/home/node/app/src/database
        ports:
            - "1982:1982"
            - "43210:43210"
        depends_on:
            - router
        links:
            - router
        restart: always
    nlp:
        build: ./nlp
        image: mika/nlp
        container_name: mika-nlp
        volumes:
            - ./database:/home/node/app/src/database
        depends_on:
            - router
        links:
            - router
        restart: always
    smarthome:
        build: ./smarthome
        image: mika/smarthome
        container_name: mika-smarthome
        volumes:
            - ./database:/home/node/app/src/database
        ports:
            - "3000:3000"
        depends_on:
            - router
        links:
            - router
        restart: always