version: '2'
services:
    kernel:
        build: ./kernel
        image: mika/kernel
        container_name: mika-kernel
        depends_on:
            - router
            - mongodb
        links:
            - mongodb
            - router
        restart: always
    nlp:
        build: ./nlp
        image: mika/nlp
        container_name: mika-nlp
        depends_on:
            - router
            - kernel
        links:
            - router
        restart: always
    router:
        build: ./router
        image: mika/router
        container_name: mika-router
        ports:
            - "4000:4000"
        restart: always
    smarthome:
        build: ./smarthome
        image: mika/smarthome
        container_name: mika-smarthome
        ports:
            - "3000:3000"
        depends_on:
            - router
            - mongodb
        links:
            - router
            - mongodb
        restart: always
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        restart: always